// Generated by CoffeeScript 1.10.0
var app;

app = require('./index');

app.get('/', function(page, model, params, next) {
  var items;
  items = model.query('items', {});
  return items.subscribe(function(err) {
    model.ref('_page.items', items);
    return page.render('home');
  });
});
