// Generated by CoffeeScript 1.9.0
(function() {
  var MyComponent;

  module.exports = MyComponent = (function() {
    function MyComponent() {}

    MyComponent.prototype.view = __dirname;

    MyComponent.prototype.name = 'k-component';

    MyComponent.prototype.init = function() {};

    MyComponent.prototype.create = function() {};

    MyComponent.prototype.destroy = function() {};

    return MyComponent;

  })();

}).call(this);
